name: Web automation workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0

    - name: Setup Gradlew
      run: chmod +x gradlew

    - name: Execute Test
      run: ./gradlew cucumber
    
